name: Java CI (compile)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"   # 네 환경에 맞춤 (JavaSE-11)
      - name: Compile all .java files
        run: |
          mkdir -p out
          files="$(git ls-files '*.java')"
          if [ -n "$files" ]; then
            javac -d out $files
          else
            echo "No Java sources found."
          fi
